server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/auth/**

        - id: admin-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/admin/**

        - id: student-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/student/**

        - id: nastavnik-service
          uri: http://localhost:8084
          predicates:
            - Path=/api/nastavnik/**

        - id: biblioteka-service
          uri: http://localhost:8085
          predicates:
            - Path=/api/biblioteka/**

        - id: osoblje
          uri: http://localhost:8089
          predicates:
            - Path=/api/osoblje/**


  logging:
    level:
      org.springframework.cloud.gateway.route.RouteDefinitionLocator: DEBUG
      org.springframework.cloud.gateway.handler.RoutePredicateHandlerMapping: DEBUG

